use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

#[derive(serde::Deserialize)]
struct Colors {
    accent: String,
    selection: String,
    muted: String,
    foreground: String,
    background: String,
    bright_foreground: String,
    red: String,
    yellow: String,
    green: String,
    cyan: String,
    blue: String,
    magenta: String,
    bright_red: String,
    bright_yellow: String,
    bright_green: String,
    bright_cyan: String,
    bright_blue: String,
    bright_magenta: String,
}

fn parse_hex(hex: &str) -> (u8, u8, u8) {
    let s = hex.trim_start_matches('#');
    assert!(s.len() == 6, "expected #rrggbb, got {hex:?}");
    let r = u8::from_str_radix(&s[0..2], 16).expect("invalid hex");
    let g = u8::from_str_radix(&s[2..4], 16).expect("invalid hex");
    let b = u8::from_str_radix(&s[4..6], 16).expect("invalid hex");
    (r, g, b)
}

fn fmt_color(hex: &str) -> String {
    let (r, g, b) = parse_hex(hex);
    format!("Color::Rgb({r}, {g}, {b})")
}

fn main() {
    let theme_dir = Path::new("themes");
    println!("cargo:rerun-if-changed={}", theme_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<(String, Colors)> = Vec::new();
    for entry in fs::read_dir(theme_dir).expect("themes/ missing") {
        let path = entry.expect("read theme entry").path();
        if path.extension().and_then(|s| s.to_str()) != Some("toml") {
            continue;
        }
        let name = path
            .file_stem()
            .expect("theme stem")
            .to_string_lossy()
            .into_owned();
        let raw = fs::read_to_string(&path).expect("read theme toml");
        let colors: Colors =
            toml::from_str(&raw).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));
        entries.push((name, colors));
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Generated by build.rs; do not edit by hand.\n");
    out.push_str("pub static BUNDLED: &[(&str, Palette)] = &[\n");
    for (name, c) in &entries {
        writeln!(out, "    (\"{name}\", Palette {{").unwrap();
        writeln!(out, "        accent: {},", fmt_color(&c.accent)).unwrap();
        writeln!(out, "        cursor: {},", fmt_color(&c.bright_foreground)).unwrap();
        writeln!(out, "        foreground: {},", fmt_color(&c.foreground)).unwrap();
        writeln!(out, "        background: {},", fmt_color(&c.background)).unwrap();
        writeln!(
            out,
            "        selection_foreground: {},",
            fmt_color(&c.bright_foreground)
        )
        .unwrap();
        writeln!(
            out,
            "        selection_background: {},",
            fmt_color(&c.selection)
        )
        .unwrap();
        writeln!(out, "        ansi: [").unwrap();
        let colors = [
            &c.background,
            &c.red,
            &c.green,
            &c.yellow,
            &c.blue,
            &c.magenta,
            &c.cyan,
            &c.foreground,
            &c.muted,
            &c.bright_red,
            &c.bright_green,
            &c.bright_yellow,
            &c.bright_blue,
            &c.bright_magenta,
            &c.bright_cyan,
            &c.bright_foreground,
        ];
        for chunk in colors.chunks(4) {
            let line: Vec<String> = chunk.iter().map(|hex| fmt_color(hex)).collect();
            writeln!(out, "            {},", line.join(", ")).unwrap();
        }
        writeln!(out, "        ],").unwrap();
        writeln!(out, "    }}),").unwrap();
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("bundled_palettes.rs");
    fs::write(dest, out).expect("write bundled_palettes.rs");

    // Emit a names-only table for `config::profile::Settings::validate` — it
    // needs the accept-list of theme slugs without pulling in the ratatui
    // `Color` type that `Palette` carries.
    let mut names = String::new();
    names.push_str("// Generated by build.rs; do not edit by hand.\n");
    names.push_str("pub static BUNDLED_THEME_NAMES: &[&str] = &[\n");
    for (name, _) in &entries {
        writeln!(names, "    \"{name}\",").unwrap();
    }
    names.push_str("];\n");
    let names_dest = Path::new(&out_dir).join("bundled_theme_names.rs");
    fs::write(names_dest, names).expect("write bundled_theme_names.rs");
}
